// Copies skills/crosscode/SKILL.md into a committed TypeScript module.
//
// The CLI has to ship the skill's text, and the repo file is the source of truth -- but four
// toolchains read apps/cli/src: `tsc --noEmit`, vitest, `tsx` (pnpm crosscode runs the source
// directly), and the esbuild bundle. A `.md` import with an esbuild text loader resolves in at
// most two of them. A generated `.ts` module works in all four with no loader configuration.
//
// Run via `pnpm generate:skill`; scripts/build.mjs runs it before bundling, and
// apps/cli/src/agent-surface.test.ts fails if the committed copy has drifted.
import { readFile, writeFile } from "node:fs/promises";

const source = new URL("../skills/crosscode/SKILL.md", import.meta.url);
const target = new URL("../apps/cli/src/skill-text.ts", import.meta.url);

const markdown = await readFile(source, "utf8");

// JSON.stringify rather than a template literal: no backtick, `${`, or backslash escaping to
// get wrong, and the result is byte-for-byte the file.
const module = `// Generated by scripts/generate-skill.mjs -- do not edit.
// Source: skills/crosscode/SKILL.md

export const SKILL_MARKDOWN = ${JSON.stringify(markdown)};
`;

await writeFile(target, module);
